apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: mysql-monitor
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: mysql
  endpoints:
    - port: metrics
      interval: 15s

