CHANGE REPLICATION SOURCE TO
  SOURCE_HOST='mysql-master',
  SOURCE_USER='replicator',
  SOURCE_PASSWORD='replica',
  SOURCE_LOG_FILE='mysql-bin.000001',
  SOURCE_LOG_POS=####;

START REPLICA;
SHOW REPLICA STATUS\G

